# Generated by Django 6.1 on 2026-08-23 16:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('account_type', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank account'), ('e_wallet', 'E-wallet'), ('credit_card', 'Credit card'), ('savings', 'Savings account'), ('loan', 'Loan account'), ('investment', 'Investment account')], max_length=20)),
                ('currency', models.CharField(default='PHP', max_length=3)),
                ('institution', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_active', 'name'],
                'constraints': [models.UniqueConstraint(fields=('user', 'name'), name='unique_account_name_per_user')],
            },
        ),
    ]
