# Generated by Django 6.1 on 2026-08-24 06:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0003_remove_category_unique_category_name_per_user_per_parent_and_more'),
        ('households', '0002_alter_household_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='categories.category')),
                ('household', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='households.household')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-month', 'category__name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='budget_amount_positive'), models.UniqueConstraint(condition=models.Q(('household__isnull', True)), fields=('user', 'category', 'month'), name='unique_personal_budget_per_user_category_month'), models.UniqueConstraint(condition=models.Q(('household__isnull', False)), fields=('household', 'category', 'month'), name='unique_shared_budget_per_household_category_month')],
            },
        ),
    ]
