# Generated by Django 6.1 on 2026-08-24 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='household',
            options={'ordering': ['name']},
        ),
    ]
