# Generated by Django 6.1 on 2026-08-24 06:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_seed_default_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='category',
            name='unique_category_name_per_user_per_parent',
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', False)), fields=('user', 'name', 'kind', 'parent'), name='unique_subcategory_name_per_user_per_parent'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', True)), fields=('user', 'name', 'kind'), name='unique_top_level_category_name_per_user'),
        ),
    ]
