# Generated by Django 6.1 on 2026-08-24 09:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filename', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed')], default='pending', max_length=10)),
                ('row_count', models.PositiveIntegerField()),
                ('date_column', models.CharField(max_length=100)),
                ('description_column', models.CharField(max_length=100)),
                ('amount_column', models.CharField(max_length=100)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_batches', to='accounts.account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw_data', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('imported', 'Imported'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=10)),
                ('error', models.CharField(blank=True, max_length=255)),
                ('is_duplicate', models.BooleanField(default=False)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='imports.importbatch')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='import_row', to='transactions.transaction')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['batch'], name='imports_imp_batch_i_258ae7_idx')],
            },
        ),
    ]
