# Generated by Django 6.1 on 2026-08-24 06:52

import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lender', models.CharField(blank=True, max_length=100)),
                ('principal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_rate', models.DecimalField(decimal_places=3, max_digits=6)),
                ('term_months', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='LoanPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('principal_portion', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_portion', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_extra', models.BooleanField(default=False)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='loans.loan')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddConstraint(
            model_name='loan',
            constraint=models.CheckConstraint(condition=models.Q(('principal__gt', 0)), name='loan_principal_positive'),
        ),
        migrations.AddConstraint(
            model_name='loan',
            constraint=models.CheckConstraint(condition=models.Q(('interest_rate__gte', 0)), name='loan_interest_rate_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='loan',
            constraint=models.CheckConstraint(condition=models.Q(('term_months__gt', 0)), name='loan_term_months_positive'),
        ),
        migrations.AddIndex(
            model_name='loanpayment',
            index=models.Index(fields=['loan', 'date'], name='loans_loanp_loan_id_fd2a7f_idx'),
        ),
        migrations.AddConstraint(
            model_name='loanpayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='loan_payment_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='loanpayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount', django.db.models.expressions.CombinedExpression(models.F('principal_portion'), '+', models.F('interest_portion')))), name='loan_payment_amount_matches_split'),
        ),
    ]
